name: Uses Cypress run action

on:
  push:
    branches:
      - luc-105789300795943

  pull_request:
    branches:
      - luc-105789300795943

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "luc-105789300795943"

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_MODE: "testops"
  QASE_DEBUG: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
